### Site info:
title: Lost Canvas
tagline: 阅读。思考。记录。
author: gelitenight
email: gelitenight@gmail.com
description: "Read. Think. Write." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "android, developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gelitenight.github.io" # the base hostname & protocol for your site
locale: cn

### Personal info and site tools info:
twitter_username: 
github_username:  gelitenight
disqus_shortname: gelitenight
favicon: "/images/favicon.ico"
aboutme: "安卓开发" # these are shown on aboutme-sidebar.
aboutme_photo: # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:


### Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "hard_wrap", "lax_spacing", "footnotes"]
paginate: 5

excerpt_separator: <!--more-->